# values-minimal.yaml
# --------------------------------------------------
# Airflow Helm chart minimal config para Minikube + WSL2
# Airflow 3 + Postgres persistente (Official PostgreSQL image)
# --------------------------------------------------

# ========================
# Disable Bitnami PostgreSQL, use official image
# ========================
postgresql:
  enabled: false

# ========================
# External PostgreSQL (using official image)
# ========================
data:
  metadataConnection:
    user: airflow
    pass: airflowpassword
    protocol: postgresql
    host: postgres
    port: 5432
    db: airflow
    sslmode: disable

# ========================
# Redis
# ========================
redis:
  enabled: true
  persistence:
    enabled: false

# ========================
# Airflow Configuration
# ========================
executor: "CeleryExecutor"

# Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
fernetKey: "n7uEZy1JQaHQZmtgty1jOg2Ywr3FZi2MyfMUjjD-C40="

# Webserver
webserver:
  replicas: 1
  service:
    type: NodePort
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Scheduler
scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Workers
workers:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Triggerer
triggerer:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# DAGs configuration - GitSync (MÉTODO PROFESIONAL)
# Para usar tu propio repo, cambia la URL por tu repositorio de GitHub/GitLab
dags:
  gitSync:
    enabled: true
    # CAMBIAR esta URL por tu repositorio real cuando lo tengas
    repo: https://github.com/apache/airflow.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    # Usar el subdirectorio de ejemplos por ahora
    subPath: "airflow/example_dags"
    wait: 60
    containerName: git-sync
    uid: 65533
    
  # Deshabilitar persistencia ya que gitSync maneja el almacenamiento
  persistence:
    enabled: false

# Logs
logs:
  persistence:
    enabled: false